version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: bash -c "
        django-admin startproject config 
        && python ./config/manage.py runserver 0.0.0.0:8000
      "