version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: bash -c "
        django-admin startproject config 
        && python ./config/manage.py runserver 0.0.0.0:8000
      "
  local-db:
    image: library/mysql:5.7
    container_name: infra-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64