# Generated by Django 4.2.4 on 2023-08-27 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(help_text='- 기호 없이 숫자만 넣어주세요.', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(9, message='전화번호는 최소 9자 이상이어야 합니다.'), django.core.validators.MaxLengthValidator(11, message='전화번호는 최대 11자까지 허용됩니다.')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
