# Generated by Django 4.2.4 on 2023-08-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(help_text='가격')),
                ('origin_price', models.PositiveIntegerField(help_text='원가')),
                ('name', models.CharField(help_text='이름', max_length=255)),
                ('name_initials', models.CharField(help_text='이름의 초성', max_length=255, null=True)),
                ('description', models.TextField(help_text='설명')),
                ('barcode', models.CharField(help_text='바코드', max_length=100)),
                ('expired_date', models.DateField(help_text='유통 기한')),
                ('size', models.CharField(choices=[('undefined', 'UNDEFINED'), ('small', 'SMALL'), ('large', 'LARGE')], default=products.models.ProductSizeType['UNDEFINED'], help_text='사이즈', max_length=30)),
                ('status', models.CharField(choices=[('undefined', 'UNDEFINED'), ('registered', 'REGISTERED'), ('deleted', 'DELETED')], default=products.models.ProductStatusType['UNDEFINED'], help_text='상태', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='카테고리 이름', max_length=40)),
                ('code', models.IntegerField(default=None, help_text='카테고리 코드', null=True, unique=True)),
                ('product', models.ManyToManyField(help_text='상품', related_name='categories', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
